book_notes = ["Before this tragedy, she used to speak to one of her friends every week; then, suddenly, the calls stopped. Almost a year later, the widow picked up the phone. “Why haven’t I heard from you?” she asked. “Oh,” explained her friend, “I wanted to wait until you felt better.” Her friend didn’t understand that withholding comfort actually added to the pain.\\n\\nOctober 16, 2017", "But when someone is suffering, instead of following the Golden Rule, we need to follow the Platinum Rule: 6 treat others as they want to be treated. Take a cue from the person in distress and respond with understanding— or better yet, action. As I was struggling to get back on my feet at home and at work, friends and colleagues would graciously ask, “Is there anything I can do?” They were sincere, but for most of them, I did not have an answer. There were things that would have been helpful but it was hard for me to ask for them. And some of the requests that came to mind were way too much of an imposition. Can you make sure my children and I are never left alone on any holiday?\\n\\nOctober 16, 2017", "“What do you NOT want on a burger?” Dan appreciated the effort. “Instead of asking if I wanted food, he made the choice for me but gave me the dignity of feeling in control.” Another friend texted Dan that she was available for a hug if he needed one and would be in the hospital lobby for the next hour whether he came downstairs or not.\\n\\nOctober 16, 2017", "Bryan Stevenson, a legal activist who leads the Equal Justice Initiative, makes the point that “we are all broken by something. 17 We have all hurt someone.” He deeply believes that “each of us is more than the worst thing we’ve ever done.”\\n\\nOctober 20, 2017", "How we spend our days,” author Annie Dillard writes, is “how we spend our lives.” 8 Rather than waiting until we’re happy to enjoy the small things, we should go and do the small things that make us happy.\\n\\nOctober 21, 2017", "As blogger Tim Urban describes it, happiness is the joy you find on hundreds of forgettable Wednesdays\\n\\nOctober 21, 2017", "Whether you see joy as a discipline, an act of defiance, a luxury, or a necessity, it is something everyone deserves. Joy allows us to go on living and loving and being there for others. Even when we’re in great distress, joy can still be found in moments we seize and moments we create. Cooking. Dancing. Hiking. Praying. Driving. Singing Billy Joel songs off-key. All of these can provide relief from pain. And when these moments add up, we find that they give us more than happiness; they also give us strength.\\n\\nNovember 9, 201"]


# for each highlight, get rid of the date.  Date range: May 17-21, 2017
notes_sans_dates = book_notes.map do |note|
  note.scan(/(?<=)(.*?)(?=\\n\\n)/).flatten.join
end

# get rid of the bookmarks
@book_highlights = notes_sans_dates.delete_if {|element| element==""}
@author = 'Sheryl Sandberg‎ & Adam Grant'
@book_title = 'Option B: Facing Adversity, Building Resilience, and Finding Joy'
@url = 'https://www.amazon.com/Option-Adversity-Building-Resilience-Finding/dp/B06W9KHNRG/ref=sr_1_1?ie=UTF8&qid=1510332331&sr=8-1&keywords=option+b'
