book_notes = ["In retrospect, my crash was one of the best things that ever happened to me because it gave me the humility I needed to balance my aggressiveness. I learned a great fear of being wrong that shifted my mind-set from thinking “I’m right” to asking myself “How do I know I’m right?” And I saw clearly that the best way to answer this question is by finding other independent thinkers who are on the same mission as me and who see things differently from me. By engaging them in thoughtful disagreement, I’d be able to understand their reasoning and have them stress-test mine.\\n\\nDecember 19, 2017", "Later in the book I will describe specific strategies for change, but the important thing to note here is that beneficial change begins when you can acknowledge and even embrace your weaknesses.\\n\\nDecember 19, 2017", "But I needed to have both low risk and high returns, and by setting out on a mission to discover how I could, I learned to go slowly when faced with the choice between two things that you need that are seemingly at odds. That way you can figure out how to have as much of both as possible. There is almost always a good path that you just haven’t discovered yet, so look for it until you find it rather than settle for the choice that is then apparent to you.\\n\\nDecember 19, 2017", "The computer was much better than my brain in “thinking” about many things at once, and it could do it more precisely, more rapidly, and less emotionally. And, because it had such a great memory, it could do a better job of compounding my knowledge and the knowledge of the people I worked with as Bridgewater grew.\\n\\nDecember 19, 2017", "The return of a market (such as the stock market) itself is called its beta. Alpha is the return that comes from betting against others. For example, some people outperform the stock market and others underperform it; they are said to have positive or negative alpha. With alpha overlay, we were offering a way of making bets independent of underlying market performance. Approaching the market in this way taught me that one of the keys to being a successful investor is to only take bets you are highly confident in and to diversify them well.\\n\\nDecember 19, 2017", "I urge you to be curious enough to want to understand how the people who see things differently from you came to see them that way. You will find that interesting and invaluable, and the richer perspective you gain will help you decide what you should do.\\n\\nDecember 19, 201"]


# for each highlight, get rid of the date.  Date range: May 17-21, 2017
notes_sans_dates = book_notes.map do |note|
  note.scan(/(?<=)(.*?)(?=\\n\\n)/).flatten.join
end

# get rid of the bookmarks
@book_highlights = notes_sans_dates.delete_if {|element| element==""}
@author = 'Ray Dalio'
@book_title = 'Principles: Life and Work'
@url = 'https://www.amazon.com/Principles-Life-Work-Ray-Dalio/dp/1501124021'
