book_notes = ["A home is a place to dwell. It’s a sanctuary that can invite us to be ourselves. Our home should be a comfortable haven, with rooms and spaces we enjoy being in. Every part of your home can be an authentic reflection of what you love\\n\\nAugust 17, 2018", "Get sentimental. Dig through your postcards and greeting cards. Hang some special notes or current family memories with pushpins or frames.\\n\\nAugust 18, 2018", "If you have a basic look you are going for, whether that be a particular era or style or basic color scheme, throw in a twist with a piece that doesn’t fit the rule so it can stand out as fresh.\\n\\nAugust 18, 2018", "When mixing styles, reduce excess clutter that can steal the show and add confusion. Remove unnecessary items off your mantel and tables.\\n\\nAugust 18, 2018", "If you were to pick your favorite escape, the place you’d go to feel refreshed, more fully alive, and in touch with what you most love, where would you go? Close your eyes and picture yourself heading there right now. Perhaps you would head to a local coffeehouse or travel to a charming seaside inn. Maybe your mind travels through time to a place you used to love. So often the highlight of the year is our vacation, the time we leave our home to go to a different place to rest and rejuvenate. Those getaways from everyday stress and routine are important, but our home is where we spend most of our time. It should be the place that nurtures us and enhances our life, perhaps as much or more than any other place on earth. With some attention to detail and a few extra touches, we can create the mood we long for right where we eat, sleep, live life, and daydream.\\n\\nAugust 18, 2018", "You see, the real secret to creating a beautiful space isn’t found in just buying the right things or even in having a perfect house to begin with. It’s in knowing how to create a place that evokes a feeling. Your home can spark happiness and comfort, joy and peace—whatever you envision as the perfect mood for your escape from the world right there in your own sanctuary.\\n\\nAugust 18, 2018", "chalkboard on the wall...[A pencil board to jot notes reminders, inspirations, drawings, and inspire community and co-creation. Even something simple like in Terrace House where you indicate where you're going when you leave to the other house guests.]\\n\\nAugust 18, 2018", "Dim lighting, natural elements, soothing music\\n\\nSpa or salon feel\\n\\nAugust 18, 2018", "vanilla and nutmeg, cloves for cozy moods,\\n\\nAugust 18, 2018", "Set a gratitude journal in the entry or living room and invite family and friends to add to it each season.\\n\\nAugust 19, 201"]


# for each highlight, get rid of the date.  Date range: May 17-21, 2017
notes_sans_dates = book_notes.map do |note|
  note.scan(/(?<=)(.*?)(?=\\n\\n)/).flatten.join
end

# get rid of the bookmarks
@book_highlights = notes_sans_dates.delete_if {|element| element==""}
@author = 'Melissa Michaels'
@book_title = 'Simple Decorating: 50 Ways to Inspire Your Home'
@url = 'https://www.amazon.com/Simple-Decorating-Inspire-Inspired-Ideas/dp/0736963111/ref=sr_1_1?ie=UTF8&qid=1535296087&sr=8-1&keywords=simple+decorating#customerReviews'
